import type { StructuredIntent } from "./providers/AIProvider";
import { useHabitStore } from "@/store/missionStore";
import { useProjectStore } from "@/store/projectStore";
import { useKnowledgeStore } from "@/store/knowledgeStore";
import { useAutomationStore } from "@/store/automationStore";
import { sanitizeCategory } from "@/constants/categories";

export interface ExecutionProposal {
  id: string;
  intent: StructuredIntent;
  title: string;
  description: string;
  actionType: "CREATE_MISSION" | "CREATE_PROJECT" | "GENERATE_NOTE" | "TRIGGER_WORKFLOW" | "OPTIMIZE_SCHEDULE";
  parameters: Record<string, any>;
  status: "PENDING" | "EXECUTED" | "CANCELLED";
  timestamp: string;
}

export function createProposalFromIntent(intent: StructuredIntent): ExecutionProposal | null {
  if (intent.intent === "UNKNOWN") return null;

  const id = `prop-${Date.now()}`;
  const timestamp = new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });

  switch (intent.intent) {
    case "CREATE_MISSION":
      return {
        id,
        intent,
        title: `Create Mission Directive: "${intent.parameters.title || "New Mission"}"`,
        description: `Add a tactical operation to Mission Control (Category: ${intent.parameters.category || "Operations"}, Priority: ${intent.parameters.priority || "Medium"}).`,
        actionType: "CREATE_MISSION",
        parameters: intent.parameters,
        status: "PENDING",
        timestamp,
      };

    case "CREATE_PROJECT":
      return {
        id,
        intent,
        title: `Create Strategic Project: "${intent.parameters.name || "New Project"}"`,
        description: `Initialize a new project initiative in Projects OS matrix.`,
        actionType: "CREATE_PROJECT",
        parameters: intent.parameters,
        status: "PENDING",
        timestamp,
      };

    case "GENERATE_NOTE":
      return {
        id,
        intent,
        title: `Generate Note: "${intent.parameters.title || "AI Note"}"`,
        description: `Save an executive document into Knowledge OS Vault.`,
        actionType: "GENERATE_NOTE",
        parameters: intent.parameters,
        status: "PENDING",
        timestamp,
      };

    case "TRIGGER_WORKFLOW":
      return {
        id,
        intent,
        title: `Trigger Automation Workflow`,
        description: `Execute active workflow rules on the Event Bus.`,
        actionType: "TRIGGER_WORKFLOW",
        parameters: intent.parameters,
        status: "PENDING",
        timestamp,
      };

    case "OPTIMIZE_SCHEDULE":
    case "GENERATE_PLAN":
      return {
        id,
        intent,
        title: `Optimize Execution Schedule`,
        description: `Recalculate time blocks and prioritize overdue operations in Time OS.`,
        actionType: "OPTIMIZE_SCHEDULE",
        parameters: intent.parameters,
        status: "PENDING",
        timestamp,
      };

    default:
      return null;
  }
}

export async function executeProposal(proposal: ExecutionProposal, userId: string): Promise<boolean> {
  const { addHabit } = useHabitStore.getState();
  const { createProject } = useProjectStore.getState();
  const { createNote } = useKnowledgeStore.getState();
  const { runWorkflowManually } = useAutomationStore.getState();

  try {
    switch (proposal.actionType) {
      case "CREATE_MISSION": {
        const cat = sanitizeCategory(proposal.parameters.category || "Operations");
        return await addHabit(userId, {
          title: proposal.parameters.title || "New AI Operation Directive",
          description: "Created via TITAN AI Commander",
          category: cat,
          priority: proposal.parameters.priority || "Medium",
          xp: 100,
          frequency: "daily",
          weeklyDays: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
        });
      }

      case "CREATE_PROJECT": {
        const today = new Date().toISOString().split("T")[0];
        createProject({
          name: proposal.parameters.name || "AI Generated Project",
          description: "Initiated via AI Commander Directive",
          category: proposal.parameters.category || "Operations",
          priority: proposal.parameters.priority || "High",
          status: "Active",
          startDate: today,
          endDate: today,
          color: "#d4af37",
          tags: ["ai-generated"],
        });
        return true;
      }

      case "GENERATE_NOTE": {
        createNote(
          proposal.parameters.title || "AI Operational Summary",
          `# ${proposal.parameters.title || "AI Note"}\n\n*Generated by TITAN AI Commander*\n\n1. Systems nominal.\n2. All operational metrics verified.`,
          "Document",
          "Operations",
          ["ai", "summary"]
        );
        return true;
      }

      case "TRIGGER_WORKFLOW": {
        const firstWf = useAutomationStore.getState().workflows[0];
        if (firstWf) {
          runWorkflowManually(firstWf.id);
        }
        return true;
      }

      case "OPTIMIZE_SCHEDULE": {
        return true;
      }

      default:
        return false;
    }
  } catch (err) {
    console.error("Failed to execute proposal:", err);
    return false;
  }
}
